version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        user: laraveluser
        uid: 1000
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
